code_assist_endpoint = "http://gcli-api.sukaka.top:7446/"
credentials_dir = "geminicli/creds"
proxy = ""
auto_ban_enabled = true
auto_ban_error_codes = [ 400, 403,]
calls_per_rotation = 10
http_timeout = 30
max_connections = 100
