name: Build and Push to GHCR

on:
  push:
    branches: [ master ]   # 当 master 分支有提交时触发

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # 推送镜像需要这个权限

    steps:
      - name: lowercase repository name
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:latest
